# Sample App Hosted on 3 nodes swarm cluster. 

version : "3"

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 3

  redis:
    image: redis:6.0
    networks:
      - frontend

  worker:
    image: bretfisher/examplevotingapp_vote:latest
    networks: 
      - backend
      - frontend

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
  
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - backend
    ports:
      - "5001:80"
      
volumes:
  db-data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
