# Sample App v2 Hosted on 3 nodes swarm cluster. 

version : "3"

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 2

  redis:
    image: redis:6.0
    networks:
      - frontend
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure


  worker:
    image: bretfisher/examplevotingapp_vote:latest
    networks: 
      - backend
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints: [node.role == manager] 

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]  
    
  
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - backend
    ports:
      - "5000:80"
      
volumes:
  db-data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay